version: '3.1'
services:
    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=test_database
            - MYSQL_USER=username
            - MYSQL_PASSWORD=password
        volumes:
            - ./phpdocker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./phpdocker/mysql/db:/var/lib/mysql
            #    - ./app/db/SQL:/docker-entrypoint-initdb.d/:rw
        ports:
            - '3306:3306'

    webserver:
        image: 'webdevops/nginx'
        working_dir: /app
        environment:
            WEB_DOCUMENT_ROOT: /app/public
            WEB_DOCUMENT_INDEX: index.php
            WEB_PHP_SOCKET: php-fpm:9000
        volumes:
            - '.:/app'
        ports:
            - '8080:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
